// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates an email to report privacy violations.
 *
 * - generatePrivacyViolationEmail - A function that generates the email.
 * - PrivacyViolationEmailInput - The input type for the generatePrivacyViolationEmail function.
 * - PrivacyViolationEmailOutput - The return type for the generatePrivacyViolationEmail function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PrivacyViolationEmailInputSchema = z.object({
  violator: z.string().describe('The username of the alleged violator.'),
  victim: z.string().describe('The username of the victim.'),
  details: z.string().describe('A detailed description of the privacy violation.'),
  policySection: z.string().describe('The specific section of the UCoC that was violated (e.g., §3.1).'),
  additionalContext: z.string().optional().describe('Any additional context or information.'),
});
export type PrivacyViolationEmailInput = z.infer<typeof PrivacyViolationEmailInputSchema>;

const PrivacyViolationEmailOutputSchema = z.object({
  emailSubject: z.string().describe('The subject of the email.'),
  emailBody: z.string().describe('The body of the email.'),
});
export type PrivacyViolationEmailOutput = z.infer<typeof PrivacyViolationEmailOutputSchema>;

export async function generatePrivacyViolationEmail(input: PrivacyViolationEmailInput): Promise<PrivacyViolationEmailOutput> {
  return generatePrivacyViolationEmailFlow(input);
}

const prompt = ai.definePrompt({
  name: 'privacyViolationEmailPrompt',
  input: {schema: PrivacyViolationEmailInputSchema},
  output: {schema: PrivacyViolationEmailOutputSchema},
  prompt: `You are an AI assistant specialized in drafting emails for reporting privacy violations to the Wikimedia Privacy Team.

  Given the details of the violation, generate a professional and concise email.

  Subject: VIOLATION OF PRIVACY - UCoC {{{policySection}}} (pt.wiki)

  To: Privacy Team

  Details:
  Violator: {{{violator}}}
  Victim: {{{victim}}}
  Violation Details: {{{details}}}
  Policy Section Violated: UCoC {{{policySection}}}

  Additional Context: {{{additionalContext}}}

Please generate an email subject and body based on this information. The email should clearly state the violation, the parties involved, and the relevant policy section.

  Output the email subject and body as a JSON object.
  `,
});

const generatePrivacyViolationEmailFlow = ai.defineFlow(
  {
    name: 'generatePrivacyViolationEmailFlow',
    inputSchema: PrivacyViolationEmailInputSchema,
    outputSchema: PrivacyViolationEmailOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
